# Generated by Django 3.2.16 on 2022-12-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20221226_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='upload',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
