# Generated by Django 3.2.16 on 2022-12-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_user_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='upload',
        ),
        migrations.AddField(
            model_name='user',
            name='profilePicture',
            field=models.ImageField(null=True, upload_to='', verbose_name='Profile Picture'),
        ),
    ]
