# Generated by Django 3.2.16 on 2022-12-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20221229_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePicture',
            field=models.ImageField(null=True, upload_to='profileImages', verbose_name='Profile Picture'),
        ),
    ]
