# Generated by Django 3.2.16 on 2023-01-02 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_user_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes', verbose_name='Resume'),
        ),
    ]
