# Generated by Django 3.2.16 on 2023-01-02 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0016_alter_job_user'),
        ('account', '0015_user_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Category_user', to='jobapp.category'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profilePicture',
            field=models.ImageField(blank=True, default='profileImages/no-profile-picture-icon.webp', null=True, upload_to='profileImages', verbose_name='Profile Picture'),
        ),
    ]
