# Generated by Django 3.2.16 on 2023-01-02 15:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20230102_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='experiences',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='qualifications',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
