# Generated by Django 3.2.16 on 2023-01-03 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_user_profilepicture'),
        ('account', '0018_auto_20230103_1242'),
    ]

    operations = [
    ]
