# Generated by Django 3.2.16 on 2023-01-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20230103_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='notifyMode',
        ),
        migrations.AddField(
            model_name='user',
            name='updateViaEmail',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updateViaPhoneNumber',
            field=models.BooleanField(default=True),
        ),
    ]
