# Generated by Django 3.2.16 on 2023-01-03 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_merge_20230103_1430'),
        ('account', '0021_auto_20230103_1846'),
    ]

    operations = [
    ]
