# Generated by Django 3.2.16 on 2023-01-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0016_alter_job_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_image',
            field=models.ImageField(blank=True, default='profileImages/no-profile-picture-icon.webp', null=True, upload_to='companyImage', verbose_name='Company Image'),
        ),
    ]
